version: '3.9'
services:
  next:
    build: next
    ports:
      - 3000:3000
    volumes:
      - ./next:/app
    command: npm run dev
  nginx:
    build: nginx
    ports:
      - 80:80
    depends_on:
      - next